language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
script: python test.py
notifications:
  irc:
    - "irc.freenode.org#medecau"
  on_success: change
  on_failure: always
  template:
      - "[%{build_number}] %{message} (%{build_url})"